# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Gregoire\Documents\PythonCode\JCAP\JCAPCreateExperimentAndFOM\QtDesign\SearchFolderForm.ui'
#
# Created: Mon May 11 23:31:21 2015
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SearchFolderDialog(object):
    def setupUi(self, SearchFolderDialog):
        SearchFolderDialog.setObjectName(_fromUtf8("SearchFolderDialog"))
        SearchFolderDialog.resize(735, 316)
        self.FolderPushButton = QtGui.QPushButton(SearchFolderDialog)
        self.FolderPushButton.setGeometry(QtCore.QRect(150, 30, 93, 21))
        self.FolderPushButton.setObjectName(_fromUtf8("FolderPushButton"))
        self.PathlistPushButton = QtGui.QPushButton(SearchFolderDialog)
        self.PathlistPushButton.setGeometry(QtCore.QRect(490, 29, 141, 21))
        self.PathlistPushButton.setObjectName(_fromUtf8("PathlistPushButton"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(SearchFolderDialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 351, 248))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.TechTypeRadioButton_0 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_0.setText(_fromUtf8(""))
        self.TechTypeRadioButton_0.setObjectName(_fromUtf8("TechTypeRadioButton_0"))
        self.FoldersButtonGroup = QtGui.QButtonGroup(SearchFolderDialog)
        self.FoldersButtonGroup.setObjectName(_fromUtf8("FoldersButtonGroup"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_0)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_0)
        self.TechTypeRadioButton_1 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_1.setText(_fromUtf8(""))
        self.TechTypeRadioButton_1.setObjectName(_fromUtf8("TechTypeRadioButton_1"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_1)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_1)
        self.TechTypeRadioButton_2 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_2.setText(_fromUtf8(""))
        self.TechTypeRadioButton_2.setObjectName(_fromUtf8("TechTypeRadioButton_2"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_2)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_2)
        self.TechTypeRadioButton_3 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_3.setText(_fromUtf8(""))
        self.TechTypeRadioButton_3.setObjectName(_fromUtf8("TechTypeRadioButton_3"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_3)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_3)
        self.TechTypeRadioButton_4 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_4.setText(_fromUtf8(""))
        self.TechTypeRadioButton_4.setObjectName(_fromUtf8("TechTypeRadioButton_4"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_4)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_4)
        self.TechTypeRadioButton_5 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_5.setText(_fromUtf8(""))
        self.TechTypeRadioButton_5.setObjectName(_fromUtf8("TechTypeRadioButton_5"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_5)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_5)
        self.TechTypeRadioButton_6 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_6.setText(_fromUtf8(""))
        self.TechTypeRadioButton_6.setObjectName(_fromUtf8("TechTypeRadioButton_6"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_6)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_6)
        self.TechTypeRadioButton_7 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_7.setText(_fromUtf8(""))
        self.TechTypeRadioButton_7.setObjectName(_fromUtf8("TechTypeRadioButton_7"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_7)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_7)
        self.TechTypeRadioButton_8 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_8.setText(_fromUtf8(""))
        self.TechTypeRadioButton_8.setObjectName(_fromUtf8("TechTypeRadioButton_8"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_8)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_8)
        self.TechTypeRadioButton_9 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_9.setText(_fromUtf8(""))
        self.TechTypeRadioButton_9.setObjectName(_fromUtf8("TechTypeRadioButton_9"))
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_9)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_9)
        self.verticalLayoutWidget = QtGui.QWidget(SearchFolderDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 50, 351, 248))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_2.addWidget(self.label_14)
        self.CheckBox_0 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_0.setText(_fromUtf8(""))
        self.CheckBox_0.setObjectName(_fromUtf8("CheckBox_0"))
        self.verticalLayout_2.addWidget(self.CheckBox_0)
        self.CheckBox_1 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_1.setText(_fromUtf8(""))
        self.CheckBox_1.setObjectName(_fromUtf8("CheckBox_1"))
        self.verticalLayout_2.addWidget(self.CheckBox_1)
        self.CheckBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_2.setText(_fromUtf8(""))
        self.CheckBox_2.setObjectName(_fromUtf8("CheckBox_2"))
        self.verticalLayout_2.addWidget(self.CheckBox_2)
        self.CheckBox_3 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_3.setText(_fromUtf8(""))
        self.CheckBox_3.setObjectName(_fromUtf8("CheckBox_3"))
        self.verticalLayout_2.addWidget(self.CheckBox_3)
        self.CheckBox_4 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_4.setText(_fromUtf8(""))
        self.CheckBox_4.setObjectName(_fromUtf8("CheckBox_4"))
        self.verticalLayout_2.addWidget(self.CheckBox_4)
        self.CheckBox_5 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_5.setText(_fromUtf8(""))
        self.CheckBox_5.setObjectName(_fromUtf8("CheckBox_5"))
        self.verticalLayout_2.addWidget(self.CheckBox_5)
        self.CheckBox_6 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_6.setText(_fromUtf8(""))
        self.CheckBox_6.setObjectName(_fromUtf8("CheckBox_6"))
        self.verticalLayout_2.addWidget(self.CheckBox_6)
        self.CheckBox_7 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_7.setText(_fromUtf8(""))
        self.CheckBox_7.setObjectName(_fromUtf8("CheckBox_7"))
        self.verticalLayout_2.addWidget(self.CheckBox_7)
        self.CheckBox_8 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_8.setText(_fromUtf8(""))
        self.CheckBox_8.setObjectName(_fromUtf8("CheckBox_8"))
        self.verticalLayout_2.addWidget(self.CheckBox_8)
        self.CheckBox_9 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_9.setText(_fromUtf8(""))
        self.CheckBox_9.setObjectName(_fromUtf8("CheckBox_9"))
        self.verticalLayout_2.addWidget(self.CheckBox_9)
        self.SearchPushButton = QtGui.QPushButton(SearchFolderDialog)
        self.SearchPushButton.setGeometry(QtCore.QRect(140, 0, 61, 21))
        self.SearchPushButton.setObjectName(_fromUtf8("SearchPushButton"))
        self.ParentFolderPushButton = QtGui.QPushButton(SearchFolderDialog)
        self.ParentFolderPushButton.setGeometry(QtCore.QRect(0, 0, 131, 21))
        self.ParentFolderPushButton.setObjectName(_fromUtf8("ParentFolderPushButton"))
        self.SearchLineEdit = QtGui.QLineEdit(SearchFolderDialog)
        self.SearchLineEdit.setGeometry(QtCore.QRect(210, 0, 201, 22))
        self.SearchLineEdit.setObjectName(_fromUtf8("SearchLineEdit"))

        self.retranslateUi(SearchFolderDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchFolderDialog)

    def retranslateUi(self, SearchFolderDialog):
        SearchFolderDialog.setWindowTitle(QtGui.QApplication.translate("SearchFolderDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.FolderPushButton.setText(QtGui.QApplication.translate("SearchFolderDialog", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.PathlistPushButton.setText(QtGui.QApplication.translate("SearchFolderDialog", "Import Selected Runs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("SearchFolderDialog", "Choose folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("SearchFolderDialog", "Choose Runs to Import:", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchPushButton.setText(QtGui.QApplication.translate("SearchFolderDialog", "search", None, QtGui.QApplication.UnicodeUTF8))
        self.ParentFolderPushButton.setText(QtGui.QApplication.translate("SearchFolderDialog", "Select Parent Folder", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SearchFolderDialog = QtGui.QDialog()
    ui = Ui_SearchFolderDialog()
    ui.setupUi(SearchFolderDialog)
    SearchFolderDialog.show()
    sys.exit(app.exec_())

