# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'C:\Users\Gregoire\Documents\PythonCode\JCAP\JCAPCreateExperimentAndFOM\QtDesign\SearchFolderForm.ui'
#
# Created: Mon May 11 23:31:21 2015
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchFolderDialog(object):
    def setupUi(self, SearchFolderDialog):
        SearchFolderDialog.setObjectName("SearchFolderDialog")
        SearchFolderDialog.resize(735, 316)
        self.FolderPushButton = QtWidgets.QPushButton(SearchFolderDialog)
        self.FolderPushButton.setGeometry(QtCore.QRect(150, 30, 93, 21))
        self.FolderPushButton.setObjectName("FolderPushButton")
        self.PathlistPushButton = QtWidgets.QPushButton(SearchFolderDialog)
        self.PathlistPushButton.setGeometry(QtCore.QRect(490, 29, 141, 21))
        self.PathlistPushButton.setObjectName("PathlistPushButton")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(SearchFolderDialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 351, 248))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.TechTypeRadioButton_0 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_0.setText("")
        self.TechTypeRadioButton_0.setObjectName("TechTypeRadioButton_0")
        self.FoldersButtonGroup = QtWidgets.QButtonGroup(SearchFolderDialog)
        self.FoldersButtonGroup.setObjectName("FoldersButtonGroup")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_0)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_0)
        self.TechTypeRadioButton_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_1.setText("")
        self.TechTypeRadioButton_1.setObjectName("TechTypeRadioButton_1")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_1)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_1)
        self.TechTypeRadioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_2.setText("")
        self.TechTypeRadioButton_2.setObjectName("TechTypeRadioButton_2")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_2)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_2)
        self.TechTypeRadioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_3.setText("")
        self.TechTypeRadioButton_3.setObjectName("TechTypeRadioButton_3")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_3)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_3)
        self.TechTypeRadioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_4.setText("")
        self.TechTypeRadioButton_4.setObjectName("TechTypeRadioButton_4")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_4)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_4)
        self.TechTypeRadioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_5.setText("")
        self.TechTypeRadioButton_5.setObjectName("TechTypeRadioButton_5")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_5)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_5)
        self.TechTypeRadioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_6.setText("")
        self.TechTypeRadioButton_6.setObjectName("TechTypeRadioButton_6")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_6)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_6)
        self.TechTypeRadioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_7.setText("")
        self.TechTypeRadioButton_7.setObjectName("TechTypeRadioButton_7")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_7)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_7)
        self.TechTypeRadioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_8.setText("")
        self.TechTypeRadioButton_8.setObjectName("TechTypeRadioButton_8")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_8)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_8)
        self.TechTypeRadioButton_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.TechTypeRadioButton_9.setText("")
        self.TechTypeRadioButton_9.setObjectName("TechTypeRadioButton_9")
        self.FoldersButtonGroup.addButton(self.TechTypeRadioButton_9)
        self.verticalLayout.addWidget(self.TechTypeRadioButton_9)
        self.verticalLayoutWidget = QtWidgets.QWidget(SearchFolderDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 50, 351, 248))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.CheckBox_0 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_0.setText("")
        self.CheckBox_0.setObjectName("CheckBox_0")
        self.verticalLayout_2.addWidget(self.CheckBox_0)
        self.CheckBox_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_1.setText("")
        self.CheckBox_1.setObjectName("CheckBox_1")
        self.verticalLayout_2.addWidget(self.CheckBox_1)
        self.CheckBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_2.setText("")
        self.CheckBox_2.setObjectName("CheckBox_2")
        self.verticalLayout_2.addWidget(self.CheckBox_2)
        self.CheckBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_3.setText("")
        self.CheckBox_3.setObjectName("CheckBox_3")
        self.verticalLayout_2.addWidget(self.CheckBox_3)
        self.CheckBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_4.setText("")
        self.CheckBox_4.setObjectName("CheckBox_4")
        self.verticalLayout_2.addWidget(self.CheckBox_4)
        self.CheckBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_5.setText("")
        self.CheckBox_5.setObjectName("CheckBox_5")
        self.verticalLayout_2.addWidget(self.CheckBox_5)
        self.CheckBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_6.setText("")
        self.CheckBox_6.setObjectName("CheckBox_6")
        self.verticalLayout_2.addWidget(self.CheckBox_6)
        self.CheckBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_7.setText("")
        self.CheckBox_7.setObjectName("CheckBox_7")
        self.verticalLayout_2.addWidget(self.CheckBox_7)
        self.CheckBox_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_8.setText("")
        self.CheckBox_8.setObjectName("CheckBox_8")
        self.verticalLayout_2.addWidget(self.CheckBox_8)
        self.CheckBox_9 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CheckBox_9.setText("")
        self.CheckBox_9.setObjectName("CheckBox_9")
        self.verticalLayout_2.addWidget(self.CheckBox_9)
        self.SearchPushButton = QtWidgets.QPushButton(SearchFolderDialog)
        self.SearchPushButton.setGeometry(QtCore.QRect(140, 0, 61, 21))
        self.SearchPushButton.setObjectName("SearchPushButton")
        self.ParentFolderPushButton = QtWidgets.QPushButton(SearchFolderDialog)
        self.ParentFolderPushButton.setGeometry(QtCore.QRect(0, 0, 131, 21))
        self.ParentFolderPushButton.setObjectName("ParentFolderPushButton")
        self.SearchLineEdit = QtWidgets.QLineEdit(SearchFolderDialog)
        self.SearchLineEdit.setGeometry(QtCore.QRect(210, 0, 201, 22))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.retranslateUi(SearchFolderDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchFolderDialog)

    def retranslateUi(self, SearchFolderDialog):
        SearchFolderDialog.setWindowTitle(
            QtCore.QCoreApplication.translate("SearchFolderDialog", "Dialog", None)
        )
        self.FolderPushButton.setText(
            QtCore.QCoreApplication.translate("SearchFolderDialog", "Open Folder", None)
        )
        self.PathlistPushButton.setText(
            QtCore.QCoreApplication.translate(
                "SearchFolderDialog", "Import Selected Runs", None
            )
        )
        self.label_13.setText(
            QtCore.QCoreApplication.translate(
                "SearchFolderDialog", "Choose folder:", None
            )
        )
        self.label_14.setText(
            QtCore.QCoreApplication.translate(
                "SearchFolderDialog", "Choose Runs to Import:", None
            )
        )
        self.SearchPushButton.setText(
            QtCore.QCoreApplication.translate("SearchFolderDialog", "search", None)
        )
        self.ParentFolderPushButton.setText(
            QtCore.QCoreApplication.translate(
                "SearchFolderDialog", "Select Parent Folder", None
            )
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    SearchFolderDialog = QtWidgets.QDialog()
    ui = Ui_SearchFolderDialog()
    ui.setupUi(SearchFolderDialog)
    SearchFolderDialog.show()
    sys.exit(app.exec_())
