# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Documents\PythonCode\JCAP\JCAPDataProcess\QtDesign\CreateExpForm.ui'
#
# Created: Fri Oct 23 15:22:22 2015
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CreateExpDialog(object):
    def setupUi(self, CreateExpDialog):
        CreateExpDialog.setObjectName(_fromUtf8("CreateExpDialog"))
        CreateExpDialog.resize(1054, 818)
        self.AddMeasPushButton = QtGui.QPushButton(CreateExpDialog)
        self.AddMeasPushButton.setGeometry(QtCore.QRect(510, 10, 161, 21))
        self.AddMeasPushButton.setObjectName(_fromUtf8("AddMeasPushButton"))
        self.FilterMeasPushButton = QtGui.QPushButton(CreateExpDialog)
        self.FilterMeasPushButton.setGeometry(QtCore.QRect(510, 40, 161, 21))
        self.FilterMeasPushButton.setObjectName(_fromUtf8("FilterMeasPushButton"))
        self.ImportRunsPushButton = QtGui.QPushButton(CreateExpDialog)
        self.ImportRunsPushButton.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.ImportRunsPushButton.setObjectName(_fromUtf8("ImportRunsPushButton"))
        self.FilterRunComboBox = QtGui.QComboBox(CreateExpDialog)
        self.FilterRunComboBox.setGeometry(QtCore.QRect(510, 90, 161, 22))
        self.FilterRunComboBox.setObjectName(_fromUtf8("FilterRunComboBox"))
        self.PlateAttrEqualComboBox = QtGui.QComboBox(CreateExpDialog)
        self.PlateAttrEqualComboBox.setGeometry(QtCore.QRect(860, 30, 81, 22))
        self.PlateAttrEqualComboBox.setObjectName(_fromUtf8("PlateAttrEqualComboBox"))
        self.label = QtGui.QLabel(CreateExpDialog)
        self.label.setGeometry(QtCore.QRect(950, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.PlateAttrEqualSpinBox = QtGui.QDoubleSpinBox(CreateExpDialog)
        self.PlateAttrEqualSpinBox.setGeometry(QtCore.QRect(970, 30, 62, 22))
        self.PlateAttrEqualSpinBox.setFrame(True)
        self.PlateAttrEqualSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.PlateAttrEqualSpinBox.setDecimals(3)
        self.PlateAttrEqualSpinBox.setMinimum(-999999.0)
        self.PlateAttrEqualSpinBox.setMaximum(999999.0)
        self.PlateAttrEqualSpinBox.setObjectName(_fromUtf8("PlateAttrEqualSpinBox"))
        self.PlateAttrLessSpinBox = QtGui.QDoubleSpinBox(CreateExpDialog)
        self.PlateAttrLessSpinBox.setGeometry(QtCore.QRect(970, 60, 62, 22))
        self.PlateAttrLessSpinBox.setFrame(True)
        self.PlateAttrLessSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.PlateAttrLessSpinBox.setDecimals(3)
        self.PlateAttrLessSpinBox.setMinimum(-999999.0)
        self.PlateAttrLessSpinBox.setMaximum(999999.0)
        self.PlateAttrLessSpinBox.setObjectName(_fromUtf8("PlateAttrLessSpinBox"))
        self.PlateAttrLessComboBox = QtGui.QComboBox(CreateExpDialog)
        self.PlateAttrLessComboBox.setGeometry(QtCore.QRect(860, 60, 81, 22))
        self.PlateAttrLessComboBox.setObjectName(_fromUtf8("PlateAttrLessComboBox"))
        self.label_2 = QtGui.QLabel(CreateExpDialog)
        self.label_2.setGeometry(QtCore.QRect(950, 60, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.PlateAttrMoreSpinBox = QtGui.QDoubleSpinBox(CreateExpDialog)
        self.PlateAttrMoreSpinBox.setGeometry(QtCore.QRect(970, 90, 62, 22))
        self.PlateAttrMoreSpinBox.setFrame(True)
        self.PlateAttrMoreSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.PlateAttrMoreSpinBox.setDecimals(3)
        self.PlateAttrMoreSpinBox.setMinimum(-999999.0)
        self.PlateAttrMoreSpinBox.setMaximum(999999.0)
        self.PlateAttrMoreSpinBox.setObjectName(_fromUtf8("PlateAttrMoreSpinBox"))
        self.label_3 = QtGui.QLabel(CreateExpDialog)
        self.label_3.setGeometry(QtCore.QRect(950, 90, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.PlateAttrMoreComboBox = QtGui.QComboBox(CreateExpDialog)
        self.PlateAttrMoreComboBox.setGeometry(QtCore.QRect(860, 90, 81, 22))
        self.PlateAttrMoreComboBox.setObjectName(_fromUtf8("PlateAttrMoreComboBox"))
        self.label_6 = QtGui.QLabel(CreateExpDialog)
        self.label_6.setGeometry(QtCore.QRect(860, 10, 181, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(CreateExpDialog)
        self.label_7.setGeometry(QtCore.QRect(520, 70, 141, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ExpTextBrowser = QtGui.QTextBrowser(CreateExpDialog)
        self.ExpTextBrowser.setGeometry(QtCore.QRect(510, 430, 531, 381))
        self.ExpTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ExpTextBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ExpTextBrowser.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.ExpTextBrowser.setObjectName(_fromUtf8("ExpTextBrowser"))
        self.SaveExpPushButton = QtGui.QPushButton(CreateExpDialog)
        self.SaveExpPushButton.setGeometry(QtCore.QRect(10, 430, 71, 21))
        self.SaveExpPushButton.setObjectName(_fromUtf8("SaveExpPushButton"))
        self.ImportExpPushButton = QtGui.QPushButton(CreateExpDialog)
        self.ImportExpPushButton.setGeometry(QtCore.QRect(290, 430, 81, 21))
        self.ImportExpPushButton.setObjectName(_fromUtf8("ImportExpPushButton"))
        self.FileSearchLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.FileSearchLineEdit.setGeometry(QtCore.QRect(860, 220, 171, 20))
        self.FileSearchLineEdit.setObjectName(_fromUtf8("FileSearchLineEdit"))
        self.label_8 = QtGui.QLabel(CreateExpDialog)
        self.label_8.setGeometry(QtCore.QRect(860, 200, 171, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.SampleListLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.SampleListLineEdit.setGeometry(QtCore.QRect(860, 140, 171, 20))
        self.SampleListLineEdit.setText(_fromUtf8(""))
        self.SampleListLineEdit.setObjectName(_fromUtf8("SampleListLineEdit"))
        self.label_9 = QtGui.QLabel(CreateExpDialog)
        self.label_9.setGeometry(QtCore.QRect(860, 120, 171, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.ExpDescLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.ExpDescLineEdit.setGeometry(QtCore.QRect(650, 400, 341, 20))
        self.ExpDescLineEdit.setObjectName(_fromUtf8("ExpDescLineEdit"))
        self.label_11 = QtGui.QLabel(CreateExpDialog)
        self.label_11.setGeometry(QtCore.QRect(550, 400, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.RunPriorityLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.RunPriorityLineEdit.setGeometry(QtCore.QRect(860, 260, 171, 20))
        self.RunPriorityLineEdit.setObjectName(_fromUtf8("RunPriorityLineEdit"))
        self.label_12 = QtGui.QLabel(CreateExpDialog)
        self.label_12.setGeometry(QtCore.QRect(860, 240, 171, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.RunTypeLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.RunTypeLineEdit.setGeometry(QtCore.QRect(560, 120, 91, 20))
        self.RunTypeLineEdit.setObjectName(_fromUtf8("RunTypeLineEdit"))
        self.label_13 = QtGui.QLabel(CreateExpDialog)
        self.label_13.setGeometry(QtCore.QRect(510, 120, 51, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.RemoveRunsPushButton = QtGui.QPushButton(CreateExpDialog)
        self.RemoveRunsPushButton.setGeometry(QtCore.QRect(240, 40, 111, 21))
        self.RemoveRunsPushButton.setObjectName(_fromUtf8("RemoveRunsPushButton"))
        self.LastActionLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.LastActionLineEdit.setGeometry(QtCore.QRect(80, 10, 411, 20))
        self.LastActionLineEdit.setObjectName(_fromUtf8("LastActionLineEdit"))
        self.label_15 = QtGui.QLabel(CreateExpDialog)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.ExpTypeLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.ExpTypeLineEdit.setGeometry(QtCore.QRect(620, 340, 51, 20))
        self.ExpTypeLineEdit.setObjectName(_fromUtf8("ExpTypeLineEdit"))
        self.label_16 = QtGui.QLabel(CreateExpDialog)
        self.label_16.setGeometry(QtCore.QRect(550, 340, 91, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(CreateExpDialog)
        self.label_17.setGeometry(QtCore.QRect(690, 340, 91, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.ExpNameLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.ExpNameLineEdit.setEnabled(False)
        self.ExpNameLineEdit.setGeometry(QtCore.QRect(760, 340, 221, 20))
        self.ExpNameLineEdit.setObjectName(_fromUtf8("ExpNameLineEdit"))
        self.label_18 = QtGui.QLabel(CreateExpDialog)
        self.label_18.setGeometry(QtCore.QRect(550, 370, 91, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.UserNameLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.UserNameLineEdit.setGeometry(QtCore.QRect(620, 370, 121, 20))
        self.UserNameLineEdit.setObjectName(_fromUtf8("UserNameLineEdit"))
        self.line = QtGui.QFrame(CreateExpDialog)
        self.line.setGeometry(QtCore.QRect(510, 320, 531, 16))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.AccessLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.AccessLineEdit.setGeometry(QtCore.QRect(830, 370, 121, 20))
        self.AccessLineEdit.setObjectName(_fromUtf8("AccessLineEdit"))
        self.label_19 = QtGui.QLabel(CreateExpDialog)
        self.label_19.setGeometry(QtCore.QRect(760, 370, 91, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.ClearExpPushButton = QtGui.QPushButton(CreateExpDialog)
        self.ClearExpPushButton.setGeometry(QtCore.QRect(210, 430, 71, 21))
        self.ClearExpPushButton.setObjectName(_fromUtf8("ClearExpPushButton"))
        self.BatchComboBox = QtGui.QComboBox(CreateExpDialog)
        self.BatchComboBox.setGeometry(QtCore.QRect(650, 300, 391, 22))
        self.BatchComboBox.setObjectName(_fromUtf8("BatchComboBox"))
        self.BatchPushButton = QtGui.QPushButton(CreateExpDialog)
        self.BatchPushButton.setGeometry(QtCore.QRect(510, 300, 131, 21))
        self.BatchPushButton.setObjectName(_fromUtf8("BatchPushButton"))
        self.line_2 = QtGui.QFrame(CreateExpDialog)
        self.line_2.setGeometry(QtCore.QRect(510, 280, 531, 16))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.ImportExpParamsPushButton = QtGui.QPushButton(CreateExpDialog)
        self.ImportExpParamsPushButton.setGeometry(QtCore.QRect(380, 430, 121, 21))
        self.ImportExpParamsPushButton.setObjectName(_fromUtf8("ImportExpParamsPushButton"))
        self.SearchRunsPushButton = QtGui.QPushButton(CreateExpDialog)
        self.SearchRunsPushButton.setGeometry(QtCore.QRect(120, 40, 111, 21))
        self.SearchRunsPushButton.setObjectName(_fromUtf8("SearchRunsPushButton"))
        self.RunTreeWidget = QtGui.QTreeWidget(CreateExpDialog)
        self.RunTreeWidget.setGeometry(QtCore.QRect(10, 70, 491, 351))
        self.RunTreeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.RunTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.RunTreeWidget.setHeaderHidden(True)
        self.RunTreeWidget.setExpandsOnDoubleClick(False)
        self.RunTreeWidget.setObjectName(_fromUtf8("RunTreeWidget"))
        self.RunTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.RunTreeWidget.header().setVisible(False)
        self.RunTreeWidget.header().setCascadingSectionResizes(False)
        self.RunTreeWidget.header().setStretchLastSection(True)
        self.ExpTreeWidget = QtGui.QTreeWidget(CreateExpDialog)
        self.ExpTreeWidget.setGeometry(QtCore.QRect(10, 460, 491, 351))
        self.ExpTreeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ExpTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ExpTreeWidget.setHeaderHidden(True)
        self.ExpTreeWidget.setExpandsOnDoubleClick(False)
        self.ExpTreeWidget.setObjectName(_fromUtf8("ExpTreeWidget"))
        self.ExpTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.ExpTreeWidget.header().setVisible(False)
        self.ExpTreeWidget.header().setCascadingSectionResizes(False)
        self.ExpTreeWidget.header().setStretchLastSection(True)
        self.label_20 = QtGui.QLabel(CreateExpDialog)
        self.label_20.setGeometry(QtCore.QRect(860, 160, 171, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.FileStartLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.FileStartLineEdit.setGeometry(QtCore.QRect(860, 180, 171, 20))
        self.FileStartLineEdit.setObjectName(_fromUtf8("FileStartLineEdit"))
        self.SaveExpGoAnaPushButton = QtGui.QPushButton(CreateExpDialog)
        self.SaveExpGoAnaPushButton.setGeometry(QtCore.QRect(90, 430, 101, 21))
        self.SaveExpGoAnaPushButton.setObjectName(_fromUtf8("SaveExpGoAnaPushButton"))
        self.getplatemapCheckBox = QtGui.QCheckBox(CreateExpDialog)
        self.getplatemapCheckBox.setGeometry(QtCore.QRect(360, 40, 119, 31))
        self.getplatemapCheckBox.setChecked(True)
        self.getplatemapCheckBox.setObjectName(_fromUtf8("getplatemapCheckBox"))
        self.UserFOMLineEdit = QtGui.QLineEdit(CreateExpDialog)
        self.UserFOMLineEdit.setGeometry(QtCore.QRect(510, 220, 151, 20))
        self.UserFOMLineEdit.setObjectName(_fromUtf8("UserFOMLineEdit"))
        self.label_21 = QtGui.QLabel(CreateExpDialog)
        self.label_21.setGeometry(QtCore.QRect(510, 200, 141, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.TechTypeTreeWidget = QtGui.QTreeWidget(CreateExpDialog)
        self.TechTypeTreeWidget.setGeometry(QtCore.QRect(680, 30, 171, 251))
        self.TechTypeTreeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.TechTypeTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TechTypeTreeWidget.setHeaderHidden(True)
        self.TechTypeTreeWidget.setExpandsOnDoubleClick(False)
        self.TechTypeTreeWidget.setObjectName(_fromUtf8("TechTypeTreeWidget"))
        self.TechTypeTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.TechTypeTreeWidget.header().setVisible(False)
        self.TechTypeTreeWidget.header().setCascadingSectionResizes(False)
        self.TechTypeTreeWidget.header().setStretchLastSection(True)
        self.label_10 = QtGui.QLabel(CreateExpDialog)
        self.label_10.setGeometry(QtCore.QRect(680, 10, 171, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))

        self.retranslateUi(CreateExpDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateExpDialog)

    def retranslateUi(self, CreateExpDialog):
        CreateExpDialog.setWindowTitle(QtGui.QApplication.translate("CreateExpDialog", "Create EXP from RUN", None, QtGui.QApplication.UnicodeUTF8))
        self.AddMeasPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Considering all the imported RUNs, apply the below filters and add files to EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.AddMeasPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Add Measurements to EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.FilterMeasPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Considering the files already in the EXP, keep the files that meet all criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.FilterMeasPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Filter Measurments in EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportRunsPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Import multiple folders and/or .zip, each representing a RUN with a .rcp file", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportRunsPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Import RUN(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.FilterRunComboBox.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Apply all other filteres in this section to only this run", None, QtGui.QApplication.UnicodeUTF8))
        self.PlateAttrEqualComboBox.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "These are attributes from the platemap file and select values or ranges can be filtered with these 3 (in)equalities", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CreateExpDialog", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CreateExpDialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CreateExpDialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CreateExpDialog", "Require the Sample properties:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CreateExpDialog", "Only consider this RUN", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveExpPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "save .exp text file", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveExpPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Save EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportExpPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Import a .exp file, which will clear any existing EXP and RUNs and create new RUNs from the EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportExpPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Import EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSearchLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "All raw data filenames regardless of type will be searched for this string.\n"
" comma-deliminated strings will be searched separately with OR logic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CreateExpDialog", "Require filename to contain:", None, QtGui.QApplication.UnicodeUTF8))
        self.SampleListLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "This should be a single sample number of comma-deliminated list of numbers from the platemap file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CreateExpDialog", "Sample list, e.g. 3,77,111", None, QtGui.QApplication.UnicodeUTF8))
        self.ExpDescLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Comment string to be included in EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CreateExpDialog", "EXP description:", None, QtGui.QApplication.UnicodeUTF8))
        self.RunPriorityLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "comma-deliminated list of RUN indeces in tree view.\n"
"If the same filename appears in multiple runs, this sets the priorty for which is used.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("CreateExpDialog", "RUN priority (high to low):", None, QtGui.QApplication.UnicodeUTF8))
        self.RunTypeLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "When \"Add\" to EXP the files within a RUN will be marked with this type", None, QtGui.QApplication.UnicodeUTF8))
        self.RunTypeLineEdit.setText(QtGui.QApplication.translate("CreateExpDialog", "data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("CreateExpDialog", "RUN use:", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveRunsPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Import multiple folders and/or .zip, each representing a RUN with a .rcp file", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveRunsPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Remove all RUNs", None, QtGui.QApplication.UnicodeUTF8))
        self.LastActionLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Comment string to be included in EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.LastActionLineEdit.setText(QtGui.QApplication.translate("CreateExpDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("CreateExpDialog", "Last Action:", None, QtGui.QApplication.UnicodeUTF8))
        self.ExpTypeLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Comment string to be included in EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.ExpTypeLineEdit.setText(QtGui.QApplication.translate("CreateExpDialog", "eche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("CreateExpDialog", "EXP type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("CreateExpDialog", "EXP name:", None, QtGui.QApplication.UnicodeUTF8))
        self.ExpNameLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Comment string to be included in EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.ExpNameLineEdit.setText(QtGui.QApplication.translate("CreateExpDialog", "eche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("CreateExpDialog", "created by:", None, QtGui.QApplication.UnicodeUTF8))
        self.UserNameLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Comment string to be included in EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.UserNameLineEdit.setText(QtGui.QApplication.translate("CreateExpDialog", "eche", None, QtGui.QApplication.UnicodeUTF8))
        self.AccessLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Comment string to be included in EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.AccessLineEdit.setText(QtGui.QApplication.translate("CreateExpDialog", "hte", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("CreateExpDialog", "EXP access:", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearExpPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "save .exp text file", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearExpPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Clear EXP", None, QtGui.QApplication.UnicodeUTF8))
        self.BatchComboBox.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Apply all other filteres in this section to only this run", None, QtGui.QApplication.UnicodeUTF8))
        self.BatchPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Considering the files already in the EXP, keep the files that meet all criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.BatchPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Run Batch Process:", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportExpParamsPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Open a .exp file and use only the top-level params", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportExpParamsPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Import EXP Params", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchRunsPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "Import multiple folders and/or .zip, each representing a RUN with a .rcp file", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchRunsPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Search for RUNs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("CreateExpDialog", "Require filename start with:", None, QtGui.QApplication.UnicodeUTF8))
        self.FileStartLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "All raw data filenames regardless of type will be searched for this string.\n"
" comma-deliminated strings will be searched separately with OR logic", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveExpGoAnaPushButton.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "save .exp text file", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveExpGoAnaPushButton.setText(QtGui.QApplication.translate("CreateExpDialog", "Save+GoToAna", None, QtGui.QApplication.UnicodeUTF8))
        self.getplatemapCheckBox.setText(QtGui.QApplication.translate("CreateExpDialog", "Get platemaps\n"
"on RUN import", None, QtGui.QApplication.UnicodeUTF8))
        self.UserFOMLineEdit.setToolTip(QtGui.QApplication.translate("CreateExpDialog", "enter comma-delimited list of string or\n"
"number FOMS that will become a constant column in the .csv generated by \"Analyze Data\".\n"
"After entry complete, you will be prompted for fom names", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("CreateExpDialog", "User-defined FOMs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CreateExpDialog", "Select tech+type to add/keep:", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CreateExpDialog = QtGui.QDialog()
    ui = Ui_CreateExpDialog()
    ui.setupUi(CreateExpDialog)
    CreateExpDialog.show()
    sys.exit(app.exec_())

